apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
spec:
  host: {{ if .Values.ui.route.host }}{{ .Values.ui.route.host }}{{ else }}{{ .Release.Name }}-ui.{{ .Values.global.namespace }}.{{ .Values.global.clusterDomain }}{{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-server
    weight: 100
  port:
    targetPort: ui
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
