apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nsw-db.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nsw-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nsw-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-credentials
                  key: password
            - name: POSTGRESQL_USER
              value: "postgres"
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.auth.databaseName | default "nsw_db" | quote }}
            - name: PGDATA
              value: /var/lib/pgsql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
