# Staging Overrides for oga-backend

replicaCount: 2

global:
  clusterDomain: "apps.sovecloud1.akaza.lk"
  namespace: "national-single-window-platform"

config:
  database:
    host: "nsw-db"
    credentialsSecretName: "nsw-db-credentials"
  nswApiBaseUrl: "http://staging-api-nsw-api:8080/api/v1"
  allowedOrigins: "https://{{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Release.Namespace }}.{{ .Values.global.clusterDomain }}"

route:
  enabled: true
  # host is omitted to allow OpenShift to generate it automatically
