{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "oga-app.fullname" . }}
  labels:
    {{- include "oga-app.labels" . | nindent 4 }}
spec:
  host: {{ if .Values.route.host }}{{ .Values.route.host }}{{ else }}{{ include "oga-app.fullname" . }}.{{ .Values.global.namespace }}.{{ .Values.global.clusterDomain }}{{ end }}
  to:
    kind: Service
    name: {{ include "oga-app.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
{{- end }}
