apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-services
data:
  services.json: |
    {
      "version": "1.0",
      "services": [
        {
          "id": "npqs",
          "url": "http://{{ .Values.config.servicePrefix }}-oga-npqs-backend.{{ .Release.Namespace }}.svc.cluster.local:8081",
          "timeout": "30s"
        },
        {
          "id": "fcau",
          "url": "http://{{ .Values.config.servicePrefix }}-oga-fcau-backend.{{ .Release.Namespace }}.svc.cluster.local:8081",
          "timeout": "30s"
        },
        {
          "id": "ird",
          "url": "http://{{ .Values.config.servicePrefix }}-oga-ird-backend.{{ .Release.Namespace }}.svc.cluster.local:8081",
          "timeout": "30s"
        },
        {
          "id": "customs-asycuda",
          "url": "https://7b0eb5f0-1ee3-4a0c-8946-82a893cb60c2.mock.pstmn.io",
          "timeout": "10s"
        },
        {
          "id": "customs-app",
          "url": "http://{{ .Values.config.servicePrefix }}customs-app.{{ .Release.Namespace }}.svc.cluster.local",
          "timeout": "5s"
        }
      ]
    }

