apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nsw-agency-backend.fullname" . }}-forms
  labels:
    {{- include "nsw-agency-backend.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.forms }}
  {{ $key | quote }}: |-
{{ $value | indent 4 }}
{{- end }}
