{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nsw-agency-backend.fullname" . }}
  labels:
    {{- include "nsw-agency-backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "nsw-agency-backend.selectorLabels" . | nindent 6 }}
{{- end }}
