apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsw-agency-backend.fullname" . }}
  labels:
    {{- include "nsw-agency-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port | default 80 }}
      targetPort: {{ .Values.config.port | default 8081 }}
      protocol: TCP
      name: http
  selector:
    {{- include "nsw-agency-backend.selectorLabels" . | nindent 4 }}
